CREATE DATABASE FastBuyOrdersDb;
GO

USE FastBuyOrdersDb;

CREATE TABLE [PRODUCT](
	PRODUCT_ID UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NAME] VARCHAR(255) NOT NULL,
	[DESCRIPTION] VARCHAR(MAX) NOT NULL,
	PRICE DECIMAL(10,2) NOT NULL,
	IS_ACTIVE BIT DEFAULT 1,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE [ORDER](
	ORDER_ID UNIQUEIDENTIFIER DEFAULT NEWID(),
	CREATE_AT DATETIME2 NOT NULL,
	CONSTRAINT PK_ORDER PRIMARY KEY(ORDER_ID)
);

CREATE TABLE [ORDER_ITEM](
	ORDER_ID UNIQUEIDENTIFIER NOT NULL,
	PRODUCT_ID UNIQUEIDENTIFIER NOT NULL,
	QUANTITY INT NOT NULL,
	CONSTRAINT PK_ORDER_ITEM PRIMARY KEY(ORDER_ID, PRODUCT_ID),
	CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY(ORDER_ID)
		REFERENCES [ORDER](ORDER_ID),
	CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY(PRODUCT_ID)
		REFERENCES [PRODUCT](PRODUCT_ID)
);

CREATE TABLE [ORDER_STATE](
	CORRELATION_ID UNIQUEIDENTIFIER NOT NULL,
	LAST_UPDATE DATETIME2 NOT NULL,
	CURRENT_STATE VARCHAR(50) NOT NULL,
	REASON_REJECTION VARCHAR(MAX),
	CONSTRAINT PK_ORDER_STATE PRIMARY KEY(CORRELATION_ID),
	CONSTRAINT FK_ORDER_STATE_ORDER FOREIGN KEY(CORRELATION_ID)
		REFERENCES [ORDER](ORDER_ID)
);
GO